# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inference_service.proto\x12\tinference\"S\n\x05Shard\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0bstart_layer\x18\x02 \x01(\x05\x12\x11\n\tend_layer\x18\x03 \x01(\x05\x12\x10\n\x08n_layers\x18\x04 \x01(\x05\"i\n\rTensorRequest\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x11\n\tis_prompt\x18\x05 \x01(\x08\"U\n\x0eTensorResponse\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x10\n\x08is_final\x18\x04 \x01(\x08\"\x07\n\x05\x45mpty\"d\n\x0cHealthStatus\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x1f\n\x05shard\x18\x02 \x01(\x0b\x32\x10.inference.Shard\x12\x11\n\tmemory_gb\x18\x03 \x01(\x02\x12\x0f\n\x07node_id\x18\x04 \x01(\t2\x96\x01\n\x10InferenceService\x12\x46\n\rProcessTensor\x12\x18.inference.TensorRequest\x1a\x19.inference.TensorResponse\"\x00\x12:\n\x0bHealthCheck\x12\x10.inference.Empty\x1a\x17.inference.HealthStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHARD']._serialized_start=38
  _globals['_SHARD']._serialized_end=121
  _globals['_TENSORREQUEST']._serialized_start=123
  _globals['_TENSORREQUEST']._serialized_end=228
  _globals['_TENSORRESPONSE']._serialized_start=230
  _globals['_TENSORRESPONSE']._serialized_end=315
  _globals['_EMPTY']._serialized_start=317
  _globals['_EMPTY']._serialized_end=324
  _globals['_HEALTHSTATUS']._serialized_start=326
  _globals['_HEALTHSTATUS']._serialized_end=426
  _globals['_INFERENCESERVICE']._serialized_start=429
  _globals['_INFERENCESERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
