cluster:
  name: "mlx-distributed-cluster"
  coordinator_device_id: mini1
  communication_backend: "grpc"

devices:
  - device_id: mini1
    hostname: localhost
    api_port: 8100
    grpc_port: 50051
    role: coordinator
    rank: 0
    capabilities:
      model: "Mac mini M2"
      memory_gb: 16  # Corrected: 16GB not 8GB
      gpu_cores: 10
      cpu_cores: 8
      cpu_performance_cores: 4
      cpu_efficiency_cores: 4
      neural_engine_cores: 16
      bandwidth_gbps: 200.0

  - device_id: mini2
    hostname: 192.168.5.2  # Thunderbolt Bridge IP for 20 Gb/s connection
    api_port: 8101
    grpc_port: 50052
    role: worker
    rank: 1
    capabilities:
      model: "Mac mini M2"
      memory_gb: 16  # Corrected: 16GB not 8GB
      gpu_cores: 10
      cpu_cores: 8
      cpu_performance_cores: 4
      cpu_efficiency_cores: 4
      neural_engine_cores: 16
      bandwidth_gbps: 200.0

  - device_id: master
    hostname: master.local
    api_port: 8102
    grpc_port: 50053
    role: worker
    rank: 2
    capabilities:
      model: "MacBook Pro M2 Max"  # Corrected: MacBook Pro not Mac Studio
      memory_gb: 48  # Corrected: 48GB not 16GB
      gpu_cores: 30
      cpu_cores: 12
      cpu_performance_cores: 8
      cpu_efficiency_cores: 4
      neural_engine_cores: 16
      bandwidth_gbps: 400.0

model:
  name: "mlx-community/Qwen3-1.7B-8bit"
  total_layers: 28  # Qwen3-1.7B has 28 layers
  layer_distribution:
    mini1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]  # 14 layers
    mini2: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]  # 14 layers