# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Service for distributed inference
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessLayers = channel.unary_unary(
                '/mlx_inference.InferenceService/ProcessLayers',
                request_serializer=inference__pb2.LayerRequest.SerializeToString,
                response_deserializer=inference__pb2.LayerResponse.FromString,
                _registered_method=True)
        self.TransferTensor = channel.unary_unary(
                '/mlx_inference.InferenceService/TransferTensor',
                request_serializer=inference__pb2.TensorTransfer.SerializeToString,
                response_deserializer=inference__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/mlx_inference.InferenceService/HealthCheck',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/mlx_inference.InferenceService/GetDeviceInfo',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.DeviceInfo.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Service for distributed inference
    """

    def ProcessLayers(self, request, context):
        """Process layers on this worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferTensor(self, request, context):
        """Transfer tensor between nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Get device information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessLayers,
                    request_deserializer=inference__pb2.LayerRequest.FromString,
                    response_serializer=inference__pb2.LayerResponse.SerializeToString,
            ),
            'TransferTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferTensor,
                    request_deserializer=inference__pb2.TensorTransfer.FromString,
                    response_serializer=inference__pb2.TransferResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.HealthStatus.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.DeviceInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlx_inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlx_inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Service for distributed inference
    """

    @staticmethod
    def ProcessLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlx_inference.InferenceService/ProcessLayers',
            inference__pb2.LayerRequest.SerializeToString,
            inference__pb2.LayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlx_inference.InferenceService/TransferTensor',
            inference__pb2.TensorTransfer.SerializeToString,
            inference__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlx_inference.InferenceService/HealthCheck',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlx_inference.InferenceService/GetDeviceInfo',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
