# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\rmlx_inference\"\x07\n\x05\x45mpty\"\x90\x02\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x17\n\x0f\x61ssigned_layers\x18\x05 \x03(\x05\x12\x41\n\x0c\x63\x61pabilities\x18\x06 \x03(\x0b\x32+.mlx_inference.DeviceInfo.CapabilitiesEntry\x12\x17\n\x0fgpu_utilization\x18\x07 \x01(\x02\x12\x17\n\x0fmemory_usage_gb\x18\x08 \x01(\x02\x1a\x33\n\x11\x43\x61pabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\"e\n\x0eLayerRequestV2\x12+\n\x0cinput_tensor\x18\x01 \x01(\x0b\x32\x15.mlx_inference.Tensor\x12\x13\n\x0bstart_layer\x18\x02 \x01(\x05\x12\x11\n\tend_layer\x18\x03 \x01(\x05\"?\n\x0fLayerResponseV2\x12,\n\routput_tensor\x18\x01 \x01(\x0b\x32\x15.mlx_inference.Tensor\"\x83\x01\n\x0e\x46orwardRequest\x12\x11\n\tinput_ids\x18\x01 \x03(\x03\x12+\n\x0cinput_tensor\x18\x02 \x01(\x0b\x32\x15.mlx_inference.Tensor\x12\x14\n\x0cis_embedding\x18\x03 \x01(\x08\x12\x1b\n\x13is_final_projection\x18\x04 \x01(\x08\"8\n\x0f\x46orwardResponse\x12%\n\x06output\x18\x01 \x01(\x0b\x32\x15.mlx_inference.Tensor\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x02\n\x10InferenceService\x12N\n\rProcessLayers\x12\x1d.mlx_inference.LayerRequestV2\x1a\x1e.mlx_inference.LayerResponseV2\x12H\n\x07\x46orward\x12\x1d.mlx_inference.ForwardRequest\x1a\x1e.mlx_inference.ForwardResponse\x12J\n\x0bHealthCheck\x12\x1c.mlx_inference.HealthRequest\x1a\x1d.mlx_inference.HealthResponse\x12@\n\rGetDeviceInfo\x12\x14.mlx_inference.Empty\x1a\x19.mlx_inference.DeviceInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._loaded_options = None
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_DEVICEINFO']._serialized_start=44
  _globals['_DEVICEINFO']._serialized_end=316
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_start=265
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_end=316
  _globals['_TENSOR']._serialized_start=318
  _globals['_TENSOR']._serialized_end=370
  _globals['_LAYERREQUESTV2']._serialized_start=372
  _globals['_LAYERREQUESTV2']._serialized_end=473
  _globals['_LAYERRESPONSEV2']._serialized_start=475
  _globals['_LAYERRESPONSEV2']._serialized_end=538
  _globals['_FORWARDREQUEST']._serialized_start=541
  _globals['_FORWARDREQUEST']._serialized_end=672
  _globals['_FORWARDRESPONSE']._serialized_start=674
  _globals['_FORWARDRESPONSE']._serialized_end=730
  _globals['_HEALTHREQUEST']._serialized_start=732
  _globals['_HEALTHREQUEST']._serialized_end=747
  _globals['_HEALTHRESPONSE']._serialized_start=749
  _globals['_HEALTHRESPONSE']._serialized_end=798
  _globals['_INFERENCESERVICE']._serialized_start=801
  _globals['_INFERENCESERVICE']._serialized_end=1115
# @@protoc_insertion_point(module_scope)
